language: python
python:
    - "3.6"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: true
cache:
    directories:
        - "~/.platformio"


install:
    - pip install -U platformio
    - platformio update
env: 


script:
    - platformio run 

    
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: 
    - .pio/build/kt1260/firmware.bin
    - .pio/build/kt1260/firmware.elf
  skip_cleanup: true
